version: '2'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/lillydoo
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    command: /bin/bash -c "rm -rf /var/www/lillydoo/var/cache && mkdir /var/www/lillydoo/var/cache && chmod -R 777 /var/www/lillydoo/var/cache  && chmod -R 777 /var/www/lillydoo/var/logs && chmod -R 777 /var/www/lillydoo/var/sessions && nginx -g 'daemon off;'"
    networks:
      main:
        aliases:
          - web
  php:
    image: bytes85/php7.1-fpm
    volumes:
      - ./:/var/www/lillydoo
      - ./docker/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000"
    networks:
      main:
        aliases:
          - php
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db/
    networks:
      main:
        aliases:
          - db
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      main:
        aliases:
          - mailcatcher
networks:
  main:
